### ISSUE TITLE
Custom helm release name

### ISSUE THREAD

**Issue by ath88** [robusta-dev/robusta#364]
Currently, the robusta CLI expects the helm release to be called 'robusta'. We have a strict naming policy for helm charts. This means I can't use the `robusta auth gen-token`- and `robusta logs`-commands. They fail with the following errors:

```
/Error from server (NotFound): secrets "robusta-auth-config-secret" not found
```

```
Error from server (NotFound): deployments.apps "robusta-runner" not found
Traceback (most recent call last):
  File "/home/ath88/.local/bin/robusta", line 8, in <module>
    sys.exit(app())
  File "/home/ath88/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/ath88/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ath88/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ath88/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ath88/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ath88/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ath88/.local/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/ath88/.local/lib/python3.8/site-packages/robusta/cli/main.py", line 422, in logs
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'kubectl logs   deployment/robusta-runner -c runner   ' returned non-zero exit status 1.
```

The release name is used in the naming of the resources, which results in the CLI not being able to locate the resources, when a different release name is used.

**Comment by ath88** [comment]
On a side note - some objects include the release name, while others don't:

```
ath88@speirs:~/.local/lib/python3.8/site-packages/robusta$ kc get secret -n robusta
NAME                                                      TYPE                                  DATA   AGE
default-token-7bdtd                                       kubernetes.io/service-account-token   3      15d
robusta-auth-config-secret                                Opaque                                2      15d
robusta-playbooks-config-secret                           Opaque                                1      15d
robusta-release-1-forwarder-service-account-token-nbtbc   kubernetes.io/service-account-token   3      15d
robusta-release-1-runner-service-account-token-z6gxq      kubernetes.io/service-account-token   3      15d
robusta-runner-secret                                     Opaque                                1      15d
sh.helm.release.v1.robusta-release-1.v1                   helm.sh/release.v1                    1      15d
```

This may or may not be intentional.

**Comment by Sheeproid** [comment]
Thanks for providing more info.

**Comment by RoiGlinik** [comment]
@ath88 Hey I am working on a fix. I couldn't reproduce the issue `robusta auth gen-token` any chance it was another command?
https://github.com/robusta-dev/robusta/pull/404

**Comment by ath88** [comment]
`robusta auth gen-token` likely failed due to wrong namespace, but if the created resources are changed to include the release name, then it would again be an issue.
