### ISSUE TITLE
Error when performing Efficiency scan

### ISSUE THREAD

**Issue by kimbirkelund** [robusta-dev/robusta#927]
**Describe the bug**
On the Effiency page I select to Rescan my cluster and after a small while its errors with a generic "Scan error" message.

Looking at the log I find the following snippet:

```
robusta-runner-7c544b9f85-r96p2 runner 2023-06-06 11:34:15.062 ERROR    Failed to execute action krr_scan cluster_name: ret***dev, account_id: ee0***39e, alertmanager_url: htt***093, grafana_api_key: , grafana_dashboard_uid: , grafana_url: , prometheus_url: htt***090, signing_key: dc1***baf, named_sinks: ['r***k']
robusta-runner-7c544b9f85-r96p2 runner Traceback (most recent call last):
robusta-runner-7c544b9f85-r96p2 runner   File "/app/src/robusta/core/playbooks/playbooks_event_handler_impl.py", line 215, in __run_playbook_actions
robusta-runner-7c544b9f85-r96p2 runner     registered_action.func(execution_event, params)
robusta-runner-7c544b9f85-r96p2 runner   File "/usr/local/lib/python3.9/site-packages/robusta_playbooks/krr.py", line 241, in krr_scan
robusta-runner-7c544b9f85-r96p2 runner     results=[
robusta-runner-7c544b9f85-r96p2 runner   File "/usr/local/lib/python3.9/site-packages/robusta_playbooks/krr.py", line 250, in <listcomp>
robusta-runner-7c544b9f85-r96p2 runner     content=[
robusta-runner-7c544b9f85-r96p2 runner   File "/usr/local/lib/python3.9/site-packages/robusta_playbooks/krr.py", line 265, in <listcomp>
robusta-runner-7c544b9f85-r96p2 runner     "metric": scan.metrics[resource].dict(),
robusta-runner-7c544b9f85-r96p2 runner KeyError: 'cpu'
```

I've attached the full log of the run (redacting anything identifiable): [log.txt](https://github.com/robusta-dev/robusta/files/11664146/log.txt)

**Comment by arikalon1** [comment]
Thanks for reporting it @kimbirkelund 

We'll release a fix soon.

**Comment by arikalon1** [comment]
Fixed here:
https://github.com/robusta-dev/robusta/commit/dab64f126d1e743ddb881b5fb630ba327e73444b

Will be released on the next version
