### ISSUE TITLE
python_memory action throwing an Exception

### ISSUE THREAD

**Issue by vik-y** [robusta-dev/robusta#987]
**Describe the bug**
I am trying to trigger `python_memory` action via a prometheus alert. All the action in my playbooks get executed except for the `python_memory`. 

I checked the logs of robusta runner and I found this exception happening 

```
2023-07-07 10:43:57.406 ERROR could not parse json:
----------------
ERROR! Timed out after 43 seconds
Traceback (most recent call last):

File "/usr/local/bin/debug-toolkit", line 6, in <module>
sys.exit(app())

File "/app/src/debug_toolkit/main.py", line 193, in memory
inject_string(pid, payload, trampoline=True, trampoline_timeout=timeout_seconds, verbose=verbose)

File "/app/src/debug_toolkit/main.py", line 167, in inject_string
return do_trampoline_injection(pid, payload, verbose, trampoline_timeout)

File "/app/src/debug_toolkit/main.py", line 137, in do_trampoline_injection
with open(abs_done_path, "r") as f:

FileNotFoundError: [Errno 2] No such file or directory: '/proc/403997/cwd/610e2287b9706d9cb14342c8b9c02acb_done.txt'


----------------

2023-07-07 10:43:57.407 ERROR Failed to execute action python_memory cluster_name: ecl***tic, account_id: d5a***477, grafana_api_key: , grafana_dashboard_uid: , grafana_url: , prometheus_url: , signing_key: 551***c3a, seconds: 30
Traceback (most recent call last):
File "/app/src/robusta/core/playbooks/playbooks_event_handler_impl.py", line 213, in __run_playbook_actions
registered_action.func(execution_event, params)
File "/usr/local/lib/python3.9/site-packages/robusta_playbooks/pod_troubleshooting.py", line 201, in python_memory
snapshot = PythonMemorySnapshot(**load_json(output))
File "/app/src/robusta/utils/parsing.py", line 12, in load_json
return json.loads(s)
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**

This is the playbook which I have
```
customPlaybooks:
- triggers:
  - on_prometheus_alert:
      alert_name: memory_alert
  actions:
  # Get the logs from pod
  - logs_enricher: {}
  # Get ps details from inside the pod which is exiting 
  - pod_bash_enricher:
      bash_command: ps aux --sort=-%mem | awk '{ printf("%s\t%s MB\n", $11, ($6/1024)) }'
  # Now delete the pod and let it auto restart because we are using Deployment 
  - python_memory: {}
  - delete_pod: {}
 ```

Rule which fires this alert
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus-stack
  name: testalert
  namespace: default
  
spec:
  groups:
    - name: custom_alert.rules
      rules:
        - alert: memory_alert
          expr: |
            avg(container_memory_usage_bytes{container="myapp-robusta"}) by (pod) /  avg(kube_pod_container_resource_limits{resource="memory"}) by (pod) > 0.8
          labels:
            severity: warning
          annotations:
            summary: "Memory usage (instance {{ $labels.instance }})"
            description: "Memory usage is above 80% (current value is: {{ $value }})"
```

**Expected behavior**
Expected behaviour is to get the memory profiling message on slack as mentioned in this url: https://docs.robusta.dev/master/playbook-reference/actions/python-troubleshooting.html#python-memory

**Comment by StepanKuksenko** [comment]
got the same error just trying to trigger the playbook manually:
`robusta playbooks trigger python_memory name=podname namespace=default
`
is there a solution ?
